### ISSUE TITLE
Handling of datetime/timestamp params broken

### ISSUE THREAD

**Issue by dthorpe** [johntitus/node.liqui.io#6]
When passing a `since` param into the TradeHistory API
example: 
```
params = {
  since: new Date('2018-01-01'),
}
liqui.tradeHistory(params).then( trades => {...

```

, the library fails with an error like this: 

```
[..]/node_modules/node.liqui.io/index.js:58
						value = this.getTimestamp(params[key])
						            ^

TypeError: Cannot read property 'getTimestamp' of undefined
    at [..]/node_modules/node.liqui.io/index.js:58:19
    at Array.forEach (native)
    at Liqui._query ([..]/node_modules/node.liqui.io/index.js:55:25)
    at Liqui.tradeHistory ([..]/node_modules/node.liqui.io/index.js:215:15)
```

Perhaps that is supposed to be calling `_getTimestamp()` instead?

**Comment by AlexeyKorkoza** [comment]
I have created the package in which the bug is fixed.
https://github.com/AlexeyKorkoza/node-liqui
